### ISSUE TITLE
check on the latest release

### ISSUE THREAD

**Issue by chenrui333** [OpenIoTHub/gateway-go#2]
👋  just to check if `gateway-go 0.1.97` is the latest release. If so, it did not get marked as `latest release`.

![image](https://user-images.githubusercontent.com/1580956/110004073-077e3a00-7ce5-11eb-8273-9bc664bfb586.png)

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/72478

**Comment by IoTServ** [comment]
fixed

**Comment by chenrui333** [comment]
Thanks!
