### ISSUE TITLE
介绍下编译成openwrt的ipk的方法？

### ISSUE THREAD

**Issue by rxhdiy123** [OpenIoTHub/gateway-go#3]
如题，想编个用路由上

**Comment by IoTServ** [comment]
抱歉，之前没看到，有事情可以进群聊，这个软件已经有ipk了，https://github.com/openwrt/packages/tree/master/net/gateway-go  
在openwrt的snapshot源里面可以找到https://downloads.openwrt.org/snapshots/packages/，要使用直接使用snapshot源就行了
